mutation {
  deleteArticle(id:1){
    errors,
    violations{
      message,
      path,
      code
    },
    entity {
      ...on NodeArticle {
        title,
        body {
          value
        }
      }
    }
  }
}