mutation($id: String){
  deleteArticle(id: $id){
    errors,
    violations{
      message,
      path,
      code
    },
    entity {
      ...on NodeArticle {
        title,
        body {
          value
        }
      }
    }
  }
}